[package]
name = "codimate-render"
version = "0.1.0"
edition = "2021"

[dependencies]
codimate-core = { path = "../codimate-core" }
codimate-fonts = { path = "../codimate-fonts" }
codimate-glyph = { path = "../codimate-glyph" }
codimate-layout = { path = "../codimate-layout" }
tiny-skia = "0.12.0"
ab_glyph = "0.2.32"
