use std::io::Write;

fn main() {
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let mut out_file = std::fs::File::create(out.join("generated_fonts.rs")).unwrap();

    let mut entries = Vec::new();
    for entry in std::fs::read_dir("fonts").unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("ttf") {
            continue;
        }
        let name = path.file_stem().unwrap().to_str().unwrap().to_string();
        let data = std::fs::read(&path).unwrap();
        let ranges = extract_cmap_ranges(&data);
        entries.push((name, path, ranges));
    }

    entries.sort_by(|(a, _, _), (b, _, _)| a.cmp(b));

    writeln!(
        out_file,
        "// generated by build.rs — do not edit\n\
         pub(crate) mod generated {{\n\
         use crate::{{FontEntry, FontId}};\n\
         pub fn entries() -> &'static [FontEntry] {{\n\
         static ENTRIES: &[FontEntry] = &["
    )
    .unwrap();

    for (i, (name, path, ranges)) in entries.iter().enumerate() {
        let abs_path = std::fs::canonicalize(&path).unwrap();
        let font_data_path = abs_path.to_string_lossy().to_string();
        // Escape backslashes on Windows; no-op on Unix.
        let font_data_path = font_data_path.replace('\\', "\\\\");

        let mut range_items = Vec::new();
        for &(start, end) in ranges {
            range_items.push(format!("0x{start:04X}..=0x{end:04X}"));
        }
        let ranges_txt = range_items.join(", ");

        writeln!(
            out_file,
            "    FontEntry {{\n\
             id: FontId({i}),\n\
             name: \"{name}\",\n\
             data: include_bytes!(\"{font_data_path}\"),\n\
             ranges: &[{ranges_txt}],\n\
             }},",
        )
        .unwrap();
    }

    writeln!(out_file, "];\nENTRIES\n}}\n}}").unwrap();
}

fn extract_cmap_ranges(data: &[u8]) -> Vec<(u32, u32)> {
    let face = match ttf_parser::Face::parse(data, 0) {
        Ok(f) => f,
        Err(_) => return Vec::new(),
    };

    let mut codepoints: Vec<u32> = Vec::new();

    if let Some(cmap) = face.tables().cmap {
        for i in 0..cmap.subtables.len() {
            if let Some(st) = cmap.subtables.get(i) {
                st.codepoints(|cp| {
                    if cp != 0 {
                        codepoints.push(cp);
                    }
                });
            }
        }
    }

    codepoints.sort();
    codepoints.dedup();

    if codepoints.is_empty() {
        return Vec::new();
    }

    let mut ranges: Vec<(u32, u32)> = Vec::new();
    let mut start = codepoints[0];
    let mut end = codepoints[0];

    for &cp in &codepoints[1..] {
        if cp == end + 1 {
            end = cp;
        } else {
            ranges.push((start, end));
            start = cp;
            end = cp;
        }
    }
    ranges.push((start, end));

    ranges
}
