[workspace]
resolver = "2"
members = [
    "crates/codimate-core",
    "crates/codimate-animation",
    "crates/codimate-layout",
    "crates/codimate-math",
    "crates/codimate-render",
    "crates/codimate-export",
    "crates/codimate-fonts",
    "crates/codimate-glyph",
    "crates/codimate-py",
    "crates/codimate-reconcile",
]
