"""Mark Khmer word boundaries in this film's captions. Authoring-time only.

    .venv/bin/python python/examples/maxwell/segment_lines.py

Writes `lines.py`, which the film imports; the film needs no segmenter. The
words are U+200B-marked the way `archimedes/segment.py` does it, and that file
is where the segmenter is found.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "archimedes"))
import segment  # noqa: E402

# ruff: noqa: E501

NAMES = ("ផារ៉ាដេ", "អំពែរ", "ម៉ាក់ស្វិល")

RAW = {
    "question": "តើម៉ាក់ស្វិលរកឃើញសមីការទាំងនេះដោយរបៀបណា?",
    "ampere": "នៅឆ្នាំ១៨២០គេឃើញថាចរន្តអគ្គិសនីធ្វើឱ្យម្ជុលត្រីវិស័យងាក។",
    "faraday": "នៅឆ្នាំ១៨៣១ផារ៉ាដេឃើញថាការរំកិលមេដែកចូលបូប៊ីនធ្វើឱ្យមានចរន្តអគ្គិសនី។",
    "field": "ផារ៉ាដេយល់ថាដែនម៉ាញេទិចមានពិតនៅក្នុងលំហ។",
    "hole": "បន្ទុកមិនឆ្លងកាត់ចន្លោះកុងដង់សាទ័រទេ។ ច្បាប់អំពែរដើមមិនអាចពន្យល់ដែន B នៅទីនោះបាន។",
    "patch": "ម៉ាក់ស្វិលបន្ថែមតួមួយក្នុងសមីការ។ ដែនអគ្គិសនីដែលប្រែប្រួលក៏ដើរតួដូចចរន្តដែរ។",
    "wave": "E និង B ដែលប្រែប្រួលភ្ជាប់គ្នាជារលកដែលធ្វើដំណើរដោយល្បឿន c។",
    "constants": "ε0 កំណត់កម្លាំងរុញរវាងបន្ទុក។ μ0 កំណត់កម្លាំងទាញរវាងខ្សែចរន្ត។ ទាំងពីរជាថេរនៃសុញ្ញកាស។",
    "speed": "ការវាស់អគ្គិសនីនិងម៉ាញេទិចក៏ឱ្យល្បឿនជិតល្បឿនពន្លឺ។ ម៉ាក់ស្វិលសន្និដ្ឋានថាពន្លឺជារលកអេឡិចត្រូម៉ាញេទិច។",
}


def main():
    for key, raw in RAW.items():
        assert raw[-1] in "។?", f"{key}: every caption ends with ។ or ?"
    seg = segment.load_segmenter(segment.DEFAULT)
    lines = ['"""Generated by segment_lines.py — Khmer captions with word marks',
             '(U+200B) already in them. Do not edit by hand."""', "",
             "# ruff: noqa: E501", "", "SAY = {"]
    for key, raw in RAW.items():
        marked = segment.mark(raw, seg)
        for name in NAMES:  # a name is one word, whatever the dictionary thinks
            marked = re.sub("\u200b?".join(map(re.escape, name)), name, marked)
        words = [w for w in marked.replace(" ", segment.ZWSP).split(segment.ZWSP) if w]
        print(f"{key:9s} {len(words):2d}  {' | '.join(words)}")
        lines.append(f"    {key!r}: {marked!r},")
    lines.append("}")
    (HERE / "lines.py").write_text("\n".join(lines) + "\n")
    print("wrote lines.py")


main()
