"""Mark Khmer word boundaries in this film's captions. Authoring-time only.

    .venv/bin/python python/examples/year/segment_lines.py

Writes `lines.py`, which the film imports; the film needs no segmenter. The
words are U+200B-marked the way `archimedes/segment.py` does it, and that file
is where the segmenter is found.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "archimedes"))
import segment  # noqa: E402

RAW = {
    "open": "គន្លងនិងល្បឿនគោចរផ្អែកលើទិន្នន័យតារាសាស្ត្រ។",
    "scale": "ក្នុងការបង្ហាញនេះ ទំហំ និងចម្ងាយគ្រាន់តែជាតម្លៃតំណាងប៉ុណ្ណោះ។",
    "spin": "ចំណាំ៖ ល្បឿនរង្វិលក្នុងវីដេអូនេះ មិនមែនជាល្បឿនពិតទេ។",
    "perihelion": "ទីតាំងដែលផែនដីនៅជិតព្រះអាទិត្យបំផុត។",
    "march": "ទីតាំងដែលថ្ងៃនិងយប់មានរយៈពេលប្រហែលគ្នា។",
    "june": "ទីតាំងដែល នៅអឌ្ឍគោលខាងជើង ពេលថ្ងៃមានរយៈពេលវែងបំផុត។",
    "aphelion": "ទីតាំងដែល ផែនដីមានចម្ងាយឆ្ងាយពីព្រះអាទិត្យបំផុត។",
    "september": "ទីតាំងដែល ពេលថ្ងៃនិងយប់មានរយៈពេលប្រហែលគ្នាម្ដងទៀត។",
    "december": "ទីតាំងដែល នៅអឌ្ឍគោលខាងជើង ពេលថ្ងៃមានរយៈពេលខ្លីបំផុត។",
}


def main():
    for key, raw in RAW.items():
        assert raw.endswith("។"), f"{key}: every caption ends with ។"
    seg = segment.load_segmenter(segment.DEFAULT)
    lines = ['"""Generated by segment_lines.py — Khmer captions with word marks',
             '(U+200B) already in them. Do not edit by hand."""', "",
             "# ruff: noqa: E501", "", "SAY = {"]
    for key, raw in RAW.items():
        marked = segment.mark(raw, seg)
        words = [w for w in marked.replace(" ", segment.ZWSP).split(segment.ZWSP) if w]
        flag = "  <-- OVER 8" if len(words) > 8 else ""
        print(f"{key:11s} {len(words):2d}  {' | '.join(words)}{flag}")
        lines.append(f"    {key!r}: {marked!r},")
    lines.append("}")
    (HERE / "lines.py").write_text("\n".join(lines) + "\n")
    print("wrote lines.py")


main()
