[package]
name = "codimate-example-khmer-fade-wave"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codimate-effects = { path = "../../crates/codimate-effects" }
codimate-fonts = { path = "../../crates/codimate-fonts" }
codimate-glyph = { path = "../../crates/codimate-glyph" }
codimate = { path = "../../crates/codimate" }
