[package]
name = "codimate-export"
version = "0.1.0"
edition = "2021"

[dependencies]
codimate-animation = { path = "../codimate-animation" }
codimate-core = { path = "../codimate-core" }
codimate-layout = { path = "../codimate-layout" }
codimate-render = { path = "../codimate-render" }
jpeg-encoder = "0.6.1"
png = "0.18.1"

[dev-dependencies]
png = "0.18.1"
