"""Scaled dot-product attention, on real GPT-2 weights.

    python python/examples/attention/main.py

    Attention(Q, K, V) = softmax( Q Kᵀ / √dₖ ) V

The animation follows one query — the word "sat" — through that formula: the
scores, the scaling, the softmax, the whole matrix, and finally the V it has
been building weights for all along.

The equation on screen is typeset from LaTeX (`scene.formula`), not spelled
with Unicode lookalikes.

Nothing here is illustrative. The Q and K vectors in `weights.py` were taken
from a real GPT-2 after a full forward pass to layer 4, and every number on
screen is worked out from them at render time. Head 3 of that layer learned to
look back at the subject of a sentence: "sat" attends 0.96 to "cat". Head 11,
right beside it, learned only ever to look one token back.

    weights.py     Q and K, extracted once from GPT-2
    attention.py   the arithmetic — no Codimate in it
    layout.py      where things sit
    view.py        the drawing
"""

import json
from dataclasses import dataclass, field
from pathlib import Path

import codimate as cm

import attention as A
import view


# --- the state --------------------------------------------------------------


@dataclass
class Walk:
    head: str = "subject"
    stage: str = "sentence"
    query: "int | None" = None
    keys: int = 0                   # how many keys have been scored
    rows: set = field(default_factory=set)
    caption: str = ""
    said: int = 0                   # words of the caption spoken so far
    card: str = ""                  # when set, the screen is a statement card


# --- the algorithm ----------------------------------------------------------


ZWSP = "\u200b"
AUDIO = Path(__file__).resolve().parent / "audio"

# What each caption sounds like, and how long it actually takes to say.
# Generated by `tools/narrate.py`; absent until someone runs it.
SPEECH, CLIP = {}, {}
if (AUDIO / "narration.json").exists():
    for entry in json.loads((AUDIO / "narration.json").read_text()):
        SPEECH[entry["text"]] = entry["seconds"]
        CLIP[entry["text"]] = entry["file"]

# Filled in while the trace runs: one pair of event names per caption, each
# timed from its own recording.
SPOKEN = {}
beat = [0]


@cm.trace()
def explain(walk):
    """Every beat is a pair of emits: an entrance (how the scene arrives) and a
    hold (how long the viewer reads it).

    The entrance event name maps to a duration in the timing config.  Scene
    changes use "cut" (near-instant) so old and new content never overlap.
    Content that persists on a stable base (formula pen trace, score reveals,
    grid fill) keeps its own timed entrance.
    """

    def narrate():
        """Run the mark along the current caption, one word at a time.

        Each caption gets its *own* pair of event names, because each is timed
        by its own recording: the mark must reach the last word exactly as the
        voice finishes it. A per-word constant cannot do that — Khmer words
        vary in spoken length, so a fixed guess drifted up to 1.8s on a long
        line and not at all on a short one.

        Without a recording it falls back to the old estimate, so the example
        still runs for anyone who has not generated the audio.

        This is also the only place that knows these event names. A beat that
        spelled its own loop once fell out of step with it and kept emitting a
        name the Timing no longer listed, which silently took the 2-second
        default per word.
        """
        pieces = view.chunks(walk.caption)
        if not pieces:
            return

        # A caption wider than the frame runs off both edges — nothing errors,
        # it just looks broken. Say so at render time instead of silently.
        if view.caption_width(walk.caption) > 1240:
            print(f"  !! caption too wide: {walk.caption[:38]}...")

        beat[0] += 1
        slide, rest = f"slide{beat[0]}", f"rest{beat[0]}"
        spoken = SPEECH.get(walk.caption.replace(ZWSP, ""))
        per_word = spoken / len(pieces) if spoken else 0.21

        # Two events, not one: the mark slides onto the word quickly, then
        # rests there while it is read. Easing it across the whole word left it
        # in motion most of the time, so at any frame it straddled two words.
        SPOKEN[slide] = min(0.07, per_word * 0.35)
        SPOKEN[rest] = per_word - SPOKEN[slide]

        walk.said = 0
        for n in range(1, len(pieces) + 1):
            walk.said = n
            cm.emit(slide)
            cm.emit(rest)

    def act(stage=None, caption=None, card=None, *, xfade=None, hold="hold",
            **rest):
        """One beat.  ``xfade`` selects the entrance event — "cut" for hard
        scene changes, "move" for smooth reveals on a stable base, "tic" for
        quick value snaps.  Cards get a cut entrance + a static hold so they
        are actually readable."""
        if stage:
            walk.stage = stage
        if caption is not None:
            walk.caption = caption
        walk.card = card or ""
        for k, v in rest.items():
            setattr(walk, k, v)
        if card:
            cm.emit(xfade or "cut")
            cm.emit("card_hold")
            return

        # The scene arrives first, then the narration is spoken over it a word
        # at a time. The caption's own length paces the beat, so a short line
        # is a short beat — which is what stops every beat feeling identical.
        # A caption may be a tuple of lines. Each is narrated in turn over the
        # same picture, the way a subtitle continues — rather than crammed onto
        # one line, which would run past the frame on the longer ones.
        lines = (walk.caption,) if isinstance(walk.caption, str) else tuple(walk.caption)

        # Shapes cross-fade over whatever segment they enter or leave in, so a
        # caption that changes during a 0.8s move fades for 0.8s. The way to
        # make it instant is to give the change no time — a 20ms segment is one
        # frame at 60fps, which reads as a cut.
        #
        # The line is also cleared before the picture moves, so the two never
        # animate at once.
        walk.caption = ""
        walk.said = 0
        cm.emit("swap")
        cm.emit(xfade or "move")

        for line in lines:
            walk.caption = line
            walk.said = 0          # the whole line, no mark on it yet
            cm.emit("swap")
            narrate()
        cm.emit(hold)

    # --- Act 1: the sentence, the constraint, the equation -----------------
    # The opening holds the sentence alone, silent, before any of this.
    act("word", 'នៅពេល AI ឃើញ​ពាក្យ sat តើ​វា​នឹង​រកមើល​លើ​អ្វីខ្លះ​ទៀត?', query=2)
    act("mask", 'វា​អាច​មើលឃើញ​បាន​តែ​ខ្លួន​វា និង​ពាក្យ (Token) ដែល​បាន​បង្ហាញ​មុនៗ​ប៉ុណ្ណោះ')
    act("roles", 'ដូច្នេះ sat ក៏​សួរ​សំណួរ (Query) ទៅ ពាក្យ មុនៗ (Key) ឲ្យ​ឆ្លើយ')
    act("formula", (
        'នេះ​ជា​សមីការ កម្រិត​នៃ​ការ​យកចិត្តទុកដាក់ (Attention)',
        'វា​ត្រូវ​បាន​គេ​ប្រើប្រាស់​ដើម្បី​វាស់​កម្រិត​ទំនាក់ទំនង​រវាង​ពាក្យ​និង​ពាក្យ​ក្នុង​ល្បះ',
    ), xfade="move")

    # --- Act 2: one token's arithmetic -------------------------------------
    act("dot", 'យើង​ប្រៀបធៀប sat ជាមួយនឹង​ពាក្យ មុនៗ', xfade="travel")

    # Said, then shown. The mark is cleared first so nothing competes with the
    # numbers as they arrive.
    walk.said = 0
    for k in range(3):
        walk.keys = k + 1
        cm.emit("score")
    cm.emit("hold")

    act("sqrt", 'វ៉ិចទ័រ​ធំ​ធ្វើ​ឲ្យ​ទំហំ​លទ្ធផល​ជា​លេខ​ក៏​ធំ ដូច្នេះ​យើង​ត្រូវ​កាត់បន្ថយ​វា',
        xfade="tic")
    act("scale", 'ពិន្ទុ​នីមួយៗ​ត្រូវ​បាន​ចែក​នឹង $\\sqrt{d_k} = 8$ ស្មើៗ​គ្នា', xfade="tic")
    act("softmax", 'អនុវត្ត Softmax រួច​ពាក្យ​នីមួយៗ​ក្លាយជា​ចំណែក​មួយ​ក្នុង​ក្រុម​ទាំងមូល',
        xfade="tic")
    act("sum", 'ទម្ងន់​ទាំងនេះ​ពេល​សរុប​ចូលគ្នា​វា​ស្មើនឹង 1', xfade="tic")
    act("compare", (
        'បើ​យើង​មិនបាន​ចែក​នឹង $\\sqrt{d_k}$ មុន​នេះ​ទេ​យើង​នឹង​ទទួល​បាន​លទ្ធផល​បែបនេះ',
        'មានតែ 1 និង 0 បានន័យ​ថា យក ឬ មិន យក តែប៉ុណ្ណោះ',
    ), xfade="tic")

    # --- Act 3: what the weights are FOR -----------------------------------
    # Still the same token. The video does not zoom out until Act 4, and then
    # it never comes back in — one continuous widening.
    act("values", 'ពាក្យ (Token) នីមួយៗ​គឺ​សុទ្ធតែ​មាន​អត្ថន័យ (Value) របស់​វា',
        xfade="cut")
    act("mix", (
        'យើង​ច្របាច់​បញ្ចូល​នូវ​អត្ថន័យ​នីមួយៗ',
        'តម្លៃ​ភាគច្រើន​មាន​ឥទ្ធិពល​ពី​ពាក្យ cat ហើយ​ពុំសូវ​មាន​ពី​ពាក្យ​ដទៃ​ប៉ុន្មាន​ឡើយ',
    ))
    act("output", 'ឥឡូវ​ពាក្យ sat ក៏​មាន​ផ្ទុក​ព័ត៌មាន​អំពី​ពាក្យ cat',
        hold="land")         # the payoff: let it sit

    # --- Act 4: every token, the same way ----------------------------------
    walk.rows.add(walk.query)
    act("matrix", 'The cat sat ដែល​បាន​ពិភាក្សា​គឺ​គ្រាន់តែ​ជាផ្នែក​មួយ​នៃ​ម៉ាទ្រីស​ប៉ុណ្ណោះ',
        xfade="cut")

    for i in range(A.N):
        walk.rows.add(i)
    act("rows", 'ពាក្យ នីមួយៗ​បង្កើត​ទំនាក់ទំនង​ដូចៗ​គ្នា', xfade="rows_fill")

    act("whole", (
        'សង្កេតមើល​ជួរឈរ cat។ ជួរ​នេះ​ភ្លឺ​ជាង​ជួរ​ផ្សេងៗ​ទៀត។',
        'សូម្បីតែ​ពាក្យ​នៅ​ក្រោយ​ពាក្យ cat ក៏​នៅតែ​មានកម្រិត​យកចិត្តទុកដាក់​ជាមួយ cat។',
    ), xfade="tic")

    # --- Act 5: many heads -------------------------------------------------
    act("coda", 'បណ្ដាញ​រង (Head) នីមួយៗ​ប្រើ​សមីការ​តែមួយ ប៉ុន្តែ​លំនាំ​ដែល​វា​អាច​យល់​គឺ​ផ្សេងៗ​គ្នា',
        head="previous", xfade="cut")
    act("why", (
        'ដូច្នេះ​ទើប​ម៉ូដែល​មួយ​ត្រូវការ​បណ្ដាញ​រង​ច្រើន​ក្នុង​ពេល​តែមួយ​ដើម្បី​រៀន​អំពី​ទំនាក់ទំនង​ខុសៗ​គ្នា',
        'និយាយ​ដោយប្រយោល​គឺ​វា​មាន​បែងចែក​មុខងារ',
        'មួយ​ជា​អ្នក​យល់​វេយ្យាករណ៍ មួយ​ជា​អ្នក​យល់​បរិបទ ឬ​មួយទៀត​ដើម្បី​យល់​ពេលវេលា​ជាដើម។',

    ), xfade="tic", hold="land")   # the closing thought: let it sit


# --- the view ---------------------------------------------------------------


def attention_view(frame):
    scene = cm.Scene()
    view.draw(scene, frame.state)
    return scene


story = explain(Walk())          # runs the trace, which fills SPOKEN

TIMING = cm.Timing(
        default=2.0,
        # Emphasis is duration. Ordinary beats are read and left behind; the
        # two moments the whole video exists for — what "sat" becomes, and the
        # two heads side by side — hold for nearly twice as long. A constant
        # beat is what makes an explainer feel like a slideshow, however good
        # each frame is.
        events={
            "move": 0.8,
            "cut": 0.05,
            "swap": 0.02,     # a caption appearing or leaving: one frame
            "tic": 0.35,
            "travel": 1.2,    # the sentence becoming the table
            "step": 0.07,     # the mark sliding onto the next word
            "word": 0.14,     # and resting there while it is read
            "hold": 0.9,      # after the line has been said
            "land": 4.4,      # a payoff, not a step
            "score": 0.9,
            "rows_fill": 2.4,
            "card_hold": 3.0,
            # One pair per caption, timed from its own recording. Without
            # these the names are unlisted and every word silently takes
            # `default` — which is how the video once came out at 725s.
            **SPOKEN,
        },
    opening=3.0, final_hold=3.4,
)


def cue_sheet():
    """When each recording should start, in the finished video.

    Walking the same events the renderer will, so the offsets cannot disagree
    with the picture — computing them a second way is how audio drifts.
    """
    cues, at, seen = [], TIMING.opening, set()
    for event in story.events:
        if event.name.startswith("slide") and event.name not in seen:
            seen.add(event.name)
            clip = CLIP.get(getattr(event.state, "caption", "").replace(ZWSP, ""))
            if clip:
                cues.append({"file": clip, "start": round(at, 3)})
        at += TIMING.events.get(event.name, TIMING.default)
    return cues


cm.explain(trace=story, view=attention_view, timing=TIMING).render(
    "results/attention.mp4", fps=60, scale=1.5)

# `wrote <path>` on its own line: that is the contract `test_examples` reads
# to find what was produced, so anything else goes on a line of its own.
print("wrote results/attention.mp4")

if CLIP:
    cues = cue_sheet()
    (AUDIO / "cues.json").write_text(json.dumps(cues, indent=2))
    print(f"  {len(cues)} audio cues -> run tools/mix.py to lay the voice on")
else:
    print("  no narration yet — see tools/narrate.py")
