[package]
name = "codimate-previewer"
version = "0.1.0"
edition = "2021"

[dependencies]
codimate-animation = { path = "../codimate-animation" }
codimate-core = { path = "../codimate-core" }
codimate-export = { path = "../codimate-export" }
codimate-layout = { path = "../codimate-layout" }
codimate-render = { path = "../codimate-render" }
codimate-example-circle-to-square = { path = "../../examples/circle-to-square" }
codimate-example-demo = { path = "../../examples/demo" }
codimate-example-connection-pulse = { path = "../../examples/connection-pulse" }
codimate-example-matrix-mult = { path = "../../examples/matrix-mult" }
codimate-example-neural-net = { path = "../../examples/neural-net" }
codimate-example-transformer = { path = "../../examples/transformer" }
codimate-example-attention-is-all-you-need-architecture = { path = "../../examples/attention-is-all-you-need-architecture" }
codimate-example-merge-sort = { path = "../../examples/merge-sort" }
codimate-example-swap-a-b = { path = "../../examples/swap-a-b" }
codimate-example-dijkstra = { path = "../../examples/dijkstra" }
codimate-example-knapsack = { path = "../../examples/knapsack" }
codimate-example-faster-dijkstra = { path = "../../examples/faster-dijkstra" }
codimate-example-newton-laws = { path = "../../examples/newton-laws" }
minifb = { version = "0.25", default-features = false, features = ["x11"] }

[build-dependencies]
toml = "0.8"

[[bin]]
name = "codimate-previewer"
path = "src/bin/preview.rs"
