"""Authoring-time only: mark Khmer word boundaries in the Cavendish captions
and write them to lines.py, the way archimedes/segment.py does for its own
words. The film imports the result and needs no segmenter.

    .venv/bin/python python/examples/cavendish/segment_lines.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "archimedes"))
import segment  # noqa: E402

RAW = {
    # 1 — the impossible question
    "rock": "យើងអាចថ្លឹងដុំថ្មបាន។",
    "person": "យើងអាចថ្លឹងមនុស្សបាន។",
    "but_earth": "ចុះផែនដីទាំងមូលវិញ?",
    "how": "តើយើងអាចថ្លឹងផែនដីបានយ៉ាងដូចម្តេច?",
    # 2 — Newton's clue
    "apple": "ផែនដីទាញផ្លែប៉ោមឱ្យធ្លាក់ចុះ។",
    "newton": "ញូតុនបង្ហាញថា វត្ថុមានម៉ាស់ទាក់ទាញគ្នា។",
    "so_balls": "ដូច្នេះ គ្រាប់សំណពីរលើតុ",
    "pull_too": "ក៏ទាក់ទាញគ្នាដែរ។",
    # 3 — the catch
    "nothing": "ប៉ុន្តែយើងមើលមិនឃើញវាផ្លាស់ទីទេ។",
    "tiny": "ព្រោះកម្លាំងទាញនេះតិចតួចណាស់។",
    # 4 — the torsion balance
    "michell": "ចន មីឆែល បានរចនាឧបករណ៍មួយ។",
    "torsion": "ឧបករណ៍នេះហៅថា «ជញ្ជីងរមួល»។",
    "cavendish": "ហេនរី កាវេនឌីស បានប្រើវានៅឆ្នាំ ១៧៩៨។",
    "big_pulls": "គ្រាប់សំណធំទាញគ្រាប់សំណតូច។",
    "rod_turns": "គ្រាប់សំណតូចធ្វើឱ្យដងវិល។",
    "wire_twists": "ពេលដងវិល ខ្សែព្យួរក៏រមួលដែរ។",
    "back": "ខ្សែរមួលបង្វិលដងត្រឡប់វិញ។",
    "equal": "ពេលទាញនិងទប់ស្មើគ្នា ដងឈប់វិល។",
    "real": "តាមពិត មុំរមួលតូចណាស់។",
    "measurable": "ប៉ុន្តែយើងនៅតែអាចវាស់វាបាន។",
    # 5 — from a tiny twist to the planet
    "angle_force": "មុំរមួលបង្ហាញកម្លាំងទាញ F។",
    "force_G": "ពីកម្លាំង F យើងគណនាថេរទំនាញ G។",
    "G_earth": "បើដឹង G យើងអាចគណនាម៉ាស់ផែនដី។",
    "result": "ដោយវាស់មុំរមួលដ៏តូចនៃខ្សែ...",
    "result2": "យើងអាចរកម៉ាស់ផែនដីបាន។",
    # the zoom-out
    "end1": "កាវេនឌីស មិនបានដាក់ផែនដីលើជញ្ជីងទេ។",
    "end2": "គាត់វាស់តែមុំរមួលតូចនៃខ្សែ។",
    "end3": "មុំនោះជួយឱ្យដឹងម៉ាស់ផែនដីទាំងមូល។",
}


def main():
    seg = segment.load_segmenter(segment.DEFAULT)
    out = {}
    for key, raw in RAW.items():
        marked = segment.mark(raw, seg)
        # The dictionary splits these Khmer proper names into syllables.
        for split_name, whole_name in {
            "ញូ\u200bតុន": "ញូតុន",
            "មី\u200bឆែល": "មីឆែល",
            "ហេន\u200bរី": "ហេនរី",
            "កា\u200bវេន\u200bឌីស": "កាវេនឌីស",
        }.items():
            marked = marked.replace(split_name, whole_name)
        words = [w for w in marked.replace(" ", segment.ZWSP).split(segment.ZWSP) if w]
        flag = "  <-- OVER 8" if len(words) > 8 else ""
        print(f"{key:12s} {len(words):2d}  {' | '.join(words)}{flag}")
        out[key] = marked
    lines = [
        '"""Generated by segment_lines.py — Khmer captions with word marks',
        '(U+200B) already in them. Do not edit by hand."""',
        "",
        "# ruff: noqa: E501",
        "",
        "SAY = {",
    ]
    for key, marked in out.items():
        lines.append(f"    {key!r}: {marked!r},")
    lines.append("}")
    (HERE / "lines.py").write_text("\n".join(lines) + "\n")
    print("wrote lines.py")


if __name__ == "__main__":
    main()
